### ISSUE TITLE
Exit code 132 when generating HTML

### ISSUE THREAD

**Issue by MortenGregersen** [SwiftDocOrg/swift-doc#98]
When generating HTML docs the swift-doc command fails with exit code 132, but succeeds when generating markdown.

The Github Actions log can be seen here: [https://github.com/FluxorOrg/Fluxor/pull/57/checks?check_run_id=646042516]()

I tried with the swift-doc Github Action, but it fails with no error, as seen here: [https://github.com/FluxorOrg/Fluxor/runs/640091636]()

Neither way can I get it to output HTML. It works when generating HTML locally on my Mac.

**Comment by mattt** [comment]
Thanks for filing this issue, @MortenGregersen. I'm sorry that this isn't working for you at the moment. Without digging into this too much, it looks like it could be related to #78.

**Comment by mattt** [comment]
This should be fixed by #99.

@MortenGregersen I'm working to cut a new release (1.0.0-beta.3) this week, but you're welcome to try the latest in master in the meantime.

**Comment by MortenGregersen** [comment]
I tried again.

When checking out and building manually I still get the 132 exit code:
https://github.com/FluxorOrg/Fluxor/runs/695438858

And when using the Github Action I get nothing but a failed step:
https://github.com/FluxorOrg/Fluxor/runs/695463951

**Comment by mattt** [comment]
This should be fixed by #140. Holding for verification after Friday's release.
